[package]
name = "broker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.20.1"
env_logger = "0.10.1"
log = { version = "0.4.20", features = [] }
clap = "3.2.25"
