builds:
  - goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w -X {{.ModulePath}}/meta.Version={{.Version}} -X {{.ModulePath}}/meta.Commit={{.Commit}} -X {{.ModulePath}}/meta.BuildDate={{.Date}}
    main: ./MainSendergo/main.go

dockers:
    - goos: linux
      goarch: arm64
      image_templates:
      - ghcr.io/Lexxn0x3/RoboterTeam1:latest
      - ghcr.io/Lexxn0x3/RoboterTeam1:{{ .Tag }}
