builds:
  - goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w -X {{.ModulePath}}/meta.Version={{.Version}} -X {{.ModulePath}}/meta.Commit={{.Commit}} -X {{.ModulePath}}/meta.BuildDate={{.Date}}
    dir: ./mainsendergo

dockers:
    - goos: linux
      goarch: arm64
      image_templates:
      - ghcr.io/lexxn0x3/roboterteam1:latest
      - ghcr.io/lexxn0x3/roboterteam1:{{ .Tag }}
      dockerfile: mainsendergo/Dockerfile
