builds:
  - goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w -X {{.ModulePath}}/meta.Version={{.Version}} -X {{.ModulePath}}/meta.Commit={{.Commit}} -X {{.ModulePath}}/meta.BuildDate={{.Date}}
    dir: ./mainsendergo
    binary: mainsendergo
