title: Roboter Team 1
description: Documentation for Team 1
theme: just-the-docs

source: ./docs

url: https://Lexxn0x3.github.io/RoboterTeam1

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark
