name: goreleaser

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Create and Push Tag
        run: bash ./mainsendergo/tagnew.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          args: release -f .goreleaser.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
