name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - 'TcpBroker/**'
      - 'mainsendergo/**'
      - 'websocket-broker/**'

permissions:
  contents: write
  packages: write

jobs:
  changes:
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
      mainsendergo: ${{ steps.filter.outputs.mainsendergo }}
      websocket-broker: ${{ steps.filter.outputs.websocket-broker }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            rust:
              - 'TcpBroker/**'
            mainsendergo:
              - 'mainsendergo/**'
            websocket-broker:
              - 'websocket-broker/**'

  build-rust:
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repository

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Build Rust Binary
        run: |
          mkdir -p build
          RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --manifest-path repository/TcpBroker/Broker/Cargo.toml --target x86_64-unknown-linux-gnu --target-dir build/

      - name: Commit and Push Binary
        run: |
          cd repository
          git reset --hard
          git config --global user.email "mattzi@users.noreply.github.com"
          git config --global user.name "Binary Builder"
          git fetch origin binaries-branch
          git switch binaries-branch || git switch -c binaries-branch origin/binaries-branch
          rm ./build/broker
          mv ../build/x86_64-unknown-linux-gnu/release/broker ./build/broker
          git add ./build/broker
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Rust binary"
            git push -u origin binaries-branch
          fi

  build-mainsendergo:
    needs: changes
    if: ${{ needs.changes.outputs.mainsendergo == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repository

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.x'

      - name: Build Go Binary 1
        run: |
          cd repository/mainsendergo
          mkdir -p ../../build
          GOOS=linux GOARCH=arm64 go build -o ../../build/mainsendergo

      - name: Commit and Push Binary
        run: |
          cd repository
          git reset --hard
          git config --global user.email "mattzi@users.noreply.github.com"
          git config --global user.name "Binary Builder"
          git fetch origin binaries-branch
          git switch binaries-branch || git switch -c binaries-branch origin/binaries-branch
          rm ./build/mainsendergo
          mv ../build/mainsendergo ./build/mainsendergo
          git add ./build/mainsendergo
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update mainsender binary"
            git push -u origin binaries-branch
          fi


  build-websocket-broker:
    needs: changes
    if: ${{ needs.changes.outputs.websocket-broker == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repository

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.x'

      - name: Build Go Binary 2
        run: |
          cd repository/websocket-broker
          mkdir -p ../../build
          GOOS=linux go build -o ../../build/websocket-broker
          
      - name: Commit and Push Binary
        run: |
          cd repository
          git reset --hard
          git config --global user.email "mattzi@users.noreply.github.com"
          git config --global user.name "Binary Builder"
          git fetch origin binaries-branch
          git switch binaries-branch || git switch -c binaries-branch origin/binaries-branch
          rm ./build/websocket-broker
          mv ../build/websocket-broker ./build/websocket-broker
          git add ./build/websocket-broker
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update websocket binary"
            git push -u origin binaries-branch
          fi

  prepare-binaries-for-release:
    needs: [build-rust, build-mainsendergo, build-websocket-broker]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout binaries branch
        uses: actions/checkout@v4
        with:
          ref: binaries-branch

      - name: Upload Rust to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rust-binary
          path: ./build/broker
          if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Upload mainsendergo to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mainsendergo
          path: ./build/mainsendergo
          if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Upload websocket-broker to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: websocket-broker
          path: ./build/websocket-broker
          if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`

  create-release:
    needs: prepare-binaries-for-release
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts/

      - name: Set execute permission for the script
        run: chmod +x ./tagnew.sh
        
      - name: Run Tagging Script
        id: create_tag
        run: ./tagnew.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.MY_PAT }}
          tag_name: ${{ steps.create_tag.outputs.tag }}
          files: |
            ./artifacts/rust-binary/broker
            ./artifacts/mainsendergo/mainsendergo
            ./artifacts/websocket-broker/websocket-broker
