name: Mirror to GitLab

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Sync to GitLab
      run: git push git@code.siemens.com:robotgroup1/mainproject.git ${GITHUB_REF#refs/heads/}:refs/heads/${GITHUB_REF#refs/heads/}
      env:
        GIT_SSH_COMMAND: ssh -i ${{ secrets.GITLAB_SSH_KEY }}
